
apiVersion: v1
kind: Config
preferences: {}

clusters:
- cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUMvakNDQWVhZ0F3SUJBZ0lCQURBTkJna3Foa2lHOXcwQkFRc0ZBREFWTVJNd0VRWURWUVFERXdwcmRXSmwKY201bGRHVnpNQjRYRFRJeU1Ea3lOakE0TURFMU5sb1hEVE15TURreU16QTRNREUxTmxvd0ZURVRNQkVHQTFVRQpBeE1LYTNWaVpYSnVaWFJsY3pDQ0FTSXdEUVlKS29aSWh2Y05BUUVCQlFBRGdnRVBBRENDQVFvQ2dnRUJBTXJaCmxDb1JjbzRDeEdhUVpJU0ZzMHNDNndKdi9BNmQ2bHV4RDVMM0VhRExvUkEwZEJVRzdtK1k5bFFsU3hrS3d4L2IKU1hpNi81YThQUHNVTmF0WVhpWEFPSUt6VXpZN1lNcURJNmdVVjZYZzV1N0YyclR0SGd2TUhaQS9Tc0RVRmlGSwpjQ09nTzNQQnlVd2NxY1JyY0t6S25Ed3E1NzhVTEtTcFl5U252ejBJMUdKZk01NFp4K2ZkNDl6dWJMUTdZdkN4Cm9xaFI0cXlVMGpLVTVncmt3S2RmcVAycXV2Smo0Z1NBanozZ29qT2dlNlV3Z0daUWhRYWNVRmFyT1dZaWZGaysKRFRocUF6VVlsSEJJZERJU25ibmVaYnJjdVJjZy91T2ZsV2RnL2t5b3huYjVWQm9vUjhLWHQvWlpEaGtnMERQQgpYRjJNblM0SGlMSHdzcFpERlk4Q0F3RUFBYU5aTUZjd0RnWURWUjBQQVFIL0JBUURBZ0trTUE4R0ExVWRFd0VCCi93UUZNQU1CQWY4d0hRWURWUjBPQkJZRUZCU0MzWE1yM0MzWUhOUGt3Q1dUekdhSXhUc0lNQlVHQTFVZEVRUU8KTUF5Q0NtdDFZbVZ5Ym1WMFpYTXdEUVlKS29aSWh2Y05BUUVMQlFBRGdnRUJBQU1Va1hCMTRoTjFWUmx0YXdXYQpkKzBYNnJsNmE3RFlMOGl3T21ESU9zWDd6NWJkZldxYWNOYndqYlU1ZG1DMzAxVVFHQStHOHlNYXlPaWpDZzQwClFVaG04aGdSTjBlbGFvVTdsVHNpT256bC9LaTZ6cVE2MTFLNXRPVnhzdWtzUXlkZlFjNGFVNkwwOHNodjFaejkKVlh4dlNUV3o4dzlJTEtnbDdlNXd3YjhGeTFGZ1EySnd0TG8rTEUrSk4xd2FqbHc0eXROTkhacHFRWUFiZGZKQwphR0dlYktUY2d5TWU1VG1WT1pWSlpnUFFValZEenpLcnVIeHFUQjZQWHQvZkZ3MzdnS0liaGl3MFo0WnhyL2dVClZ1NEJRNm4weXFIVnBpVFcrUUJoZ1hmU2dKUVkrTmRiZnhwbmpUQVhMd0pYejJFam9vWkE3aWp0eTUzR2RFWDQKVmhvPQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
    server: https://41aac645-e514-4627-853c-58ff79505045.eu-west-1.linodelke.net:443
  name: lke73995

users:
- name: lke73995-admin
  user:
    as-user-extra: {}
    token: eyJhbGciOiJSUzI1NiIsImtpZCI6ImVpbjBsUHRsRDlVQjFkY0FFa3Vodjl2aFRnaXlvQmlUdzBRdGFVU2VrSlEifQ.eyJpc3MiOiJrdWJlcm5ldGVzL3NlcnZpY2VhY2NvdW50Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9uYW1lc3BhY2UiOiJrdWJlLXN5c3RlbSIsImt1YmVybmV0ZXMuaW8vc2VydmljZWFjY291bnQvc2VjcmV0Lm5hbWUiOiJsa2UtYWRtaW4tdG9rZW4tcTd2bDYiLCJrdWJlcm5ldGVzLmlvL3NlcnZpY2VhY2NvdW50L3NlcnZpY2UtYWNjb3VudC5uYW1lIjoibGtlLWFkbWluIiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9zZXJ2aWNlLWFjY291bnQudWlkIjoiMWE3ZDUxNTAtYjRmZi00ZjY5LTk3Y2MtZmVjNTkzZTM2OWNiIiwic3ViIjoic3lzdGVtOnNlcnZpY2VhY2NvdW50Omt1YmUtc3lzdGVtOmxrZS1hZG1pbiJ9.fnSKme1DzWDx0gW9ySkWpd_I_OP7ShcTFIVhS_Nukcs2kdlRBmF9_ScDp9yi1SwRX3f2DAJSaDcz4ny66RhpegbTUdhBUMaM99dW_RJWa4bAZVtBffc6AUpcfB5UdpGGYDDlnpSJlJldTSvHIMHoN9ld_5cItC63jFHz4Gz8nX4nLHl_WN78fjW8vw0czyxfkW71WsSbR-pJTAI3QEb9SEMdHQbagyT0vLOkaRO7aMsB-O23sLUbHqWwmzBTchPtZSfD_ygxxXHhYuPOB7l7_LfiAFAWdDj5Py2rMdPuq6wU-HuXCWj_d74IbEPkLa9xvV72s-tFqUnrY4s2raOTlA

contexts:
- context:
    cluster: lke73995
    namespace: default
    user: lke73995-admin
  name: lke73995-ctx

current-context: lke73995-ctx
